
spring.datasource.url=jdbc:mysql://practica2mysql-fedelico134-9534.d.aivencloud.com:17499/defaultdb?ssl-mode=REQUIRED
spring.datasource.username=avnadmin
spring.datasource.password=AVNS_WRX_K6K2JZvUuUblyz1
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


spring.jdbc.template.query-timeout=60

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=fedelico431@gmail.com
spring.mail.password=ainkasxifmuhdyvx
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

spring.thymeleaf.cache=false

server.port=8081